=== TheGuysBrushes/incendie/Moteur/essence_data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="essences">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="essence" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
		
	<xs:element name="essence">
		<xs:complexType>
			<xs:sequence>			
				<xs:element name="nom" type="xs:string" maxOccurs="1" />
				<xs:element name="masse-vol" type="xs:integer" maxOccurs="1" />
				<xs:element name="diametre" type="xs:float" maxOccurs="1" />
				<xs:element name="hauteur" type="xs:float" maxOccurs="1" />
				<xs:element name="age_matur" type="xs:unsignedInt" maxOccurs="1" />
				<xs:element name="isFeuillu" type="xs:boolean" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== TheGuysBrushes/incendie/build/Resources/essence_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<essences xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="essence_data.xsd">
	<essence>
		<nom>Epicea</nom>
		<masse-vol>1000</masse-vol>
		<diametre>1.25</diametre>
		<hauteur>40</hauteur>
		<age_matur>40</age_matur>
		<isFeuillu>0</isFeuillu>
	</essence>
	
	<essence>
		<nom>Hetre</nom>
		<masse-vol>1000</masse-vol>
		<diametre>1.4</diametre>
		<hauteur>20</hauteur>
		<age_matur>50</age_matur>
		<isFeuillu>1</isFeuillu>
	</essence>

<!--	
Pin_sylvestre 900 0.9 30 20 0
Sapin_blanc 940 1.3 60 30 0
Chataigner 1050 2 30 35 1
	
	<essence>
		<nom></nom>
		<masse-vol></masse-vol>
		<diametre></diametre>
		<hauteur></hauteur>
		<age_matur></age_matur>
		<isFeuillu>0</isFeuillu>
	</essence>
-->

</essences>

=== TheGuysBrushes/incendie/Moteur/essence_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<essence xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="essence_data.xsd">
	<nom>Epicea</nom>
	<masse-vol>1000</masse-vol>
	<diametre>1.25</diametre>
	<hauteur>40</hauteur>
	<age_matur>40</age_matur>
	<isFeuillu>0</isFeuillu>
</essence>
	
<essence xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="essence_data.xsd">
	<nom></nom>
	<masse-vol></masse-vol>
	<diametre></diametre>
	<hauteur></hauteur>
	<age_matur></age_matur>
	<isFeuillu>0</isFeuillu>
</essence>
